name: Frontend Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Export Sentry Token
        run: export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_TOKEN }}

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@v0.0.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/frontend_2021_1_YSNP/dist"
          strip_components: 1